### ISSUE TITLE
Cannot run Slicer CLIs in the resulting docker image

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmheat#2]
```
$ /usr/slicer/Slicer --launch /usr/slicer/lib/Slicer-4.8/cli-modules/SubtractScalarVolumes
/usr/slicer/lib/Slicer-4.8/cli-modules/SubtractScalarVolumes: error while loading shared libraries: /usr/slicer/lib/Slicer-4.8/cli-modules/libSubtractScalarVolumesLib.so: ELF file OS ABI invalid
```

@pieper do you know what is going on? I thought the above was supposed to work.

**Comment by pieper** [comment]
I know that my docker images work for that use case.  You should be able to run the following:

docker run -it stevepieper/slicer /opt/slicer/Slicer --launch SubtractScalarVolumes --help

Looks like here you are using thewtex/centos-build:latest which must behave differently.  Can you list the exact steps you followed?

**Comment by pieper** [comment]
@fedorov it took a long time to build the docker image but eventually I was able to replicate they issue you reported.  I suspect it's because @thewtex is using the oldest feasible linux (centos5) to make the build images in hopes that the resulting binaries will have the most generic support.  But that platform is too old to support binaries generated by the factory.

**Comment by fedorov** [comment]
Steve, thanks for investigating! The images are automatically built here: https://hub.docker.com/r/qiicr/dcmheat/. I will add to the readme.

I will look to upgrade then. I use @thewtex images because they have nice setup of tools, and I know all of those converters I built already have no issues.

**Comment by pieper** [comment]
Yes, @thewtex has set up a nice toolsuite for development, but for our
purposes I don't think we need to be that broad.  I would suggest using a
newer base image.  I use debian but ubuntu is also a good choice.  If any
of the tools are hard to install on a widely used linux platform that is
surely a black mark for dcmheat purposes.

**Comment by fedorov** [comment]
@pieper I completely agree

**Comment by fedorov** [comment]
So then I guess it makes sense to start from @thewtex base mentioned by @jcfr earlier -
 https://github.com/thewtex/docker-opengl/blob/master/Dockerfile (which is based on Debian Jessie, which is very recent https://github.com/dockcross/dockcross). Do you agree?

**Comment by pieper** [comment]
Sure - debian jesse is fine.  my images use the next version, debian
stretch but either would work for our purposes.

**Comment by fedorov** [comment]
resolved in recent commits
